fix($core): Cannot assign to read only property 'exports' of object (close: #869)
This is weird issue of webpack. since ClientComputedMixin was used both in server and client side,
client es module will import this commonJS module, it should work but webpack throw error: 'Uncaught
TypeError: Cannot assign to read only property 'exports' of object '#<Object>''. related issue:
https://github.com/webpack/webpack/issues/4039